global:
  export:
    channel: integration-tests
    owner: tester
  setting_overrides:
    checkout: master
    version: testing
  dependency_overrides: []
package_instances: []
test-integrations:
  scratch-folder : "_test-integrations.d"
