versions:
        "2.3.2":
                folder: "2.3.2"
        "2.3.3":
                folder: "2.3.3"
        "2.4":
                folder: "2.4"
        "2.5":
                folder: "2.5"
        "2.6":
                folder: "2.6"
        "2.6.1":
                folder: all
